#!/bin/bash

# Written By Basu Dev Adhikari

boidfile=~/.secrets/.boid.txt

function showTitle(){
	echo ""
	echo " ========== $1 =========="
	echo ""
}
networkError(){
	echo -e "\033[31m Network Problem\033[0m"
	exit 1
}

function result(){
	local msg=$(curl -4 -s 'https://iporesult.cdsc.com.np/result/result/check' \
		-H 'Content-Type: application/json'\
  		--data-raw '{"companyShareId":"'$id'","boid":"'$1'"}' \
  		--compressed | jq .message)
	[[ ${#msg} == 0 ]] && networkError
	[[ "$msg" =~ "Sorry" ]] &&
	(showTitle $2 && echo -e "\033[31m         Not alloted\033[0m") ||
	(showTitle $2 && echo -e "\033[32m           Alloted \033[0m")
}


totalIpos=$(curl -4 -s 'https://iporesult.cdsc.com.np/result/companyShares/fileUploaded' \
	 --compressed  | jq .body[])
[[ "${#totalIpos}" == 0 ]] && networkError

showTitle "All IPOS"
echo $totalIpos | jq . 
read -p "Select Company Id : " id
while read line;do
	name=$(echo $line | awk '{print $1}')
	boid=$(echo $line | awk '{print $2}')
	result $boid $name & 
done < $boidfile
echo ""
